# Generated by Django 5.2.5 on 2025-09-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_linkmapping_user_alter_clicklog_clicked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmapping',
            name='owner_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
